# Generated by Django 4.2.2 on 2023-06-21 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('familyNameKanji', models.CharField(max_length=10)),
                ('firstNameKanji', models.CharField(max_length=10)),
                ('familyNameKana', models.CharField(max_length=10)),
                ('firstNameKana', models.CharField(max_length=10)),
                ('familyNameEiji', models.CharField(max_length=10, null=True)),
                ('firstNameEiji', models.CharField(max_length=10, null=True)),
                ('employeeSex', models.IntegerField()),
                ('employeeAge', models.IntegerField()),
                ('employeeArea', models.CharField(max_length=15)),
                ('certificationList', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('totalYearOfExperience', models.IntegerField()),
                ('careerId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assignCheckFlg', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['totalYearOfExperience'],
            },
        ),
    ]
