# Generated by Django 4.2.2 on 2023-06-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReteIngenium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfomationUniteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empTargetId', models.UUIDField()),
                ('proTargetId', models.UUIDField()),
                ('projectRegisteredDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
